### ISSUE TITLE
Support for Python 3.13

### ISSUE THREAD

**Issue by art049** [CodSpeedHQ/pytest-codspeed#38]
Currently, installing the package on Python 3.13 will raise the following error because of `cffi` 1.16.0:

> 'PyErr_WriteUnraisable' declared here
> PyAPI_FUNC(void) PyErr_WriteUnraisable(PyObject \*);

This is fixed in cffi 1.17.0, but unfortunately, it's not released yet.

The fix: [https://github.com/python-cffi/cffi/issues/23](https://github.com/python-cffi/cffi/issues/23)

Currently, the only workaround is to install version `1.17.0rc1` until a new release of cffi is created.

Thanks, @sydney-runkle, for reporting the issue.

Edit: [1.17 has been released](https://github.com/python-cffi/cffi/releases/tag/v1.17.0) and we can then update the cffi dependency

**Comment by sydney-runkle** [comment]
Amazing! We'll update our CI when you guys do your next release!
